--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cryotap/BlockBlocker
build-by-default: true
branches:
- main
projects:
  BlockBlocker:
    path: ""
    icon: "PVPM.gif"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
...
