name: BlockBlocker
version: 1.0.0
api: [5.0.0]
main: Cryotap\BlockBlocker\Main
author: Cryotap
description: Block using blocks in selected worlds.

commands:
  bldisable:
    description: Block blocker editor
    usage: /bldisable
    permission: blockblocker.disable.editor

permissions:
  blockblocker.disable.editor:
    default: op
    description: Deny placing certain blocks.
  blockblocker.disable.bypass:
    default: op
    description: Bypass block denying.